build:
  version: "2.0"

accounts:
  message: "Welcome to Accounts related QA APIs"
  contactDetails:
    name: "Ali - QA Lead"
    email: "Ali@gmail.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371