build:
  version: "3.0"

accounts:
  message: "Welcome to Accounts related local APIs"
  contactDetails:
    name: "Abdallha Hamdy - Developer"
    email: "abdallha.hamdy@gmail.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345